name: Text Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "11.9.0"

      - name: Install dependencies
        run: yarn

      - name: Publish window and linux binaries
        if: runner.os != 'macOS'
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish mac binaries
        if: runner.os == 'macOS'
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove un-needed artifacts
        run: rm -r -- ./*/
        shell: bash
        working-directory: ./dist/electron-mat/Packaged

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ runner.OS }}
          path: dist/electron-mat/Packaged