name: Build Unsigned

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "11.9.0"
  
      - name: Install yarn
        run: npm install yarn --no-save

      - name: Install dependencies
        run: yarn

      - name: Publish window and linux binaries
        if: runner.os != 'macOS'
        run: yarn dist:dir
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish mac binaries
        if: runner.os == 'macOS'
        run: yarn dist:dir --publish=always 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Remaining files
        run: ls .
        shell: bash
        working-directory: ./release/

      - name: Upload Production Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ runner.OS }}-production
          path: release